### PR TITLE
bigstringaf: switch to using bigstringaf

### PR DESCRIPTION
**Pull request by seliopou**

### CODE REVIEW

**Comment by hcarty** [comment]
Looks good here too!

**Comment by samoht** [comment]
Any reason to not contribute to `cstruct` instead of re-implementing the same functions in yet an other library?

**Comment by yallop** [comment]
> redundant bounds checking

[SCNR](https://github.com/inhabitedtype/bigstringaf/issues/4)

**Comment by seliopou** [comment]
I'll fix that up. I was referring more to every other operation besides the constructors.

**Pull request merged**
