### PR TITLE
Move to jbuilder

### PR DESCRIPTION
**Pull request by rgrinberg**
Moving to jbuilder has the following consequences:

* We now have separate sub packages rather than optional dependencies (yay)
* Builds are much faster.
* Generated garbage doesn't need to be checked in.

That being said, there's a couple of downsides (for now):

* There's no good way to implement the build-test section of opam files.
* You can't check in the descr file anymore. However, opam 2.0 will make these
descr files obsolete by letting you set them directly as fields in the opam
file.

Also, it's important to review the META file jbuilder generates (somewhere in
_build)

note: I didn't test the benchmarks yet. Since I just quickly ported them now.

### CODE REVIEW

**Comment by seliopou** [comment]
@rgrinberg could you give this a rebase and another once-over? I'd be interested to start porting stuff over now.

**Comment by rgrinberg** [comment]
For good topkg support, you also need a CHANGES.md file. See https://github.com/mirage/irmin/blob/master/CHANGES.md for example.

**Comment by seliopou** [comment]
What's the purpose of including the META file from 6de325a? Does that allow OPAM users to still use the old-style package names for a time?

**Comment by seliopou** [comment]
Also, why is it not possible to check in the descr file any more?

**Comment by rgrinberg** [comment]
>  Also, why is it not possible to check in the descr file any more?

It's possible. I just added them back in. Feel free to write real descriptions for the other angstrom packages.

> What's the purpose of including the META file from https://github.com/inhabitedtype/angstrom/commit/6de325a2d15185398eff93d4891c85dce5c93af1? Does that allow OPAM users to still use the old-style package names for a time?

Yeah, this means that the only breaking changes for current users is changing their opam files and not their build systems.

**Comment by rgrinberg** [comment]
@seliopou ping

**Comment by seliopou** [comment]
Fam I got you.

**Pull request merged**
