### PR TITLE
Fixed issue inhabitedtype/angstrom#2

### PR DESCRIPTION
**Pull request by latticetower**

### CODE REVIEW

**Comment by seliopou** [comment]
Great, thanks!

**Comment by seliopou** [comment]
@latticetower Did you come across any environment setup/build difficulties?

**Comment by latticetower** [comment]
@seliopou I've got this error message (the same as described [here](https://github.com/matijapretnar/eff/issues/14)):
```
./configure --enable-tests
E: Field 'findlib_version' is not set: Field 'ocamlfind' is not set
```
 + several other unresolved dependencies while installing `ocamlfind` via apt-get.

Switching to ocaml 4.02.1 and reinstalling package dependencies fixed that problem for me.

**Comment by seliopou** [comment]
Have you installed [OPAM](http://opam.ocaml.org)? If so, I would suggest using it to manage all your OCaml dependencies, including `ocamlfind`. It'll be a much smoother experience that way.

Also, if you do end up using OPAM, you should install the `aspcud` package, which is an external constraint solver that the `opam` command will detect and automatically use. It's much better than the built-in solver.

**Pull request merged**
