### PR TITLE
Add fold_scan

### PR DESCRIPTION
**Pull request by rgrinberg**
Like attoparsec's scan but returns the final state rather than the string. This
is more flexible and can implement the original scan easily.

This is to get the ball rolling on the folding discussion. This combinator can
easily be used to implement something like parsing a quoted string, which is my
concrete motivation for adding this.

PS: a better name is needed

### CODE REVIEW

**Comment by hcarty** [comment]
Would it make sense to have a signature like the following so that the fold can happen over something other than `char`s?  Possibly as an additional function.
```
val fold : 'state -> 'atom t -> ('state -> 'atom -> 'state option) -> 'state t
```
Regarding the name, is there any reason to not use `fold`?

**Comment by rgrinberg** [comment]
I usually think of a fold as something with a very precise signature. In this case, the fold can terminate early by returning None so it doesn't quite qualify.

I think adding your fold function makes sense as well. Will add it once @seliopou chimes in

**Comment by seliopou** [comment]
The upside of `fold_scan`, as it's currently called, is that it can be implemented without the use of backtracking, whereas I believe `fold` cannot; if the `atom` parser fails, the parser has to return the current accumulated state. The signature of `fold` also suggests there are two ways to terminate the parser: through the failure of the `atom` parser, and from the function returning `None`. This could be confusing to users. It should be discussed more in a separate issue before an implementation gets sent in a PR.

**Comment by seliopou** [comment]
Looks like three related parser constructors could be included:

```ocaml
val scan : 'state -> ('state -> char -> 'state option) -> (string * 'state) t
val scan_state : 'state -> ('state -> char -> 'state option) -> 'state t
val scan_string : 'state -> ('state -> char -> 'state option) -> string t
```

Of course `scan_state` shouldn't allocate any string in the process. If you have the motivation to include them, feel free to do so. Otherwise I'll do it after this is merged.

P.S. `scan` sounds like a good enough name for now.

**Comment by seliopou** [comment]
Thanks!

**Pull request merged**
